# Libraries

In [51]:
import pandas as pd

## Reading to .csv

In [52]:
dfMVP = pd.read_csv('../data/all_MVP.csv')
dfSeasons = pd.read_csv('../data/season_stats.csv')

## Renane Columns - DfMVP

In [60]:
dfMVP.rename(columns={'Player':'MVP'}, inplace=True)

## Merge DfSeasons and DfMVP

In [63]:
df = pd.merge(left = dfSeasons, right = dfMVP[['Season','MVP']], how='left', left_on=['Season', 'Player'], right_on=['Season', 'MVP'])

## Review

In [66]:
df

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,Year,Season,MVP
0,1,Kareem Abdul-Jabbar*,C,37,LAL,79,79,2630,723,1207,...,622,249,63,162,197,238,1735,1985,1984-85,NaN
1,2,Alvan Adams,PF,30,PHO,82,69,2136,476,915,...,500,308,115,48,197,254,1202,1985,1984-85,NaN
2,3,Mark Aguirre,SF,25,DAL,80,79,2699,794,1569,...,477,249,60,24,253,250,2055,1985,1984-85,NaN
3,4,Danny Ainge,SG,25,BOS,75,73,2564,419,792,...,268,399,122,6,149,228,971,1985,1984-85,NaN
4,5,Chuck Aleksinas,C,25,GSW,74,4,1114,161,337,...,270,36,15,15,72,171,377,1985,1984-85,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19118,525,Trae Young,PG,21,ATL,60,60,2120,546,1249,...,255,560,65,8,289,104,1778,2020,2019-20,NaN
19119,526,Cody Zeller,C,27,CHO,58,39,1341,251,479,...,411,88,40,25,75,140,642,2020,2019-20,NaN
19120,527,Tyler Zeller,C,30,SAS,2,0,4,1,4,...,4,0,0,0,0,0,2,2020,2019-20,NaN
19121,528,Ante Žižić,C,23,CLE,22,0,221,41,72,...,66,6,7,5,10,27,96,2020,2019-20,NaN
19122,529,Ivica Zubac,C,22,LAC,72,70,1326,236,385,...,543,82,16,66,61,168,596,2020,2019-20,NaN

In [65]:
df[~df['MVP'].isnull()]

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,Year,Season,MVP
10988,302,Dirk Nowitzki,PF,28,DAL,78,78,2820,673,1341,...,693,263,52,62,167,171,1916,2007,2006-07,Dirk Nowitzki
12028,208,LeBron James,SF,24,CLE,81,81,3054,789,1613,...,613,587,137,93,241,139,2304,2009,2008-09,LeBron James
12623,222,LeBron James,SF,25,CLE,76,76,2966,768,1528,...,554,651,125,77,261,119,2258,2010,2009-10,LeBron James
13406,356,Derrick Rose,PG,22,CHI,81,81,3026,711,1597,...,330,623,85,51,278,136,2026,2011,2010-11,Derrick Rose
13809,233,LeBron James,SF,27,MIA,62,62,2326,621,1169,...,492,387,115,50,213,96,1683,2012,2011-12,LeBron James
14346,212,LeBron James,PF,28,MIA,76,76,2877,765,1354,...,610,551,129,67,226,110,2036,2013,2012-13,LeBron James
14850,134,Kevin Durant,SF,25,OKC,81,81,3122,849,1688,...,598,445,103,59,285,174,2593,2014,2013-14,Kevin Durant
15411,112,Stephen Curry,PG,26,GSW,80,80,2613,653,1341,...,341,619,163,16,249,158,1900,2015,2014-15,Stephen Curry
16043,105,Stephen Curry,PG,27,GSW,79,79,2700,805,1598,...,430,527,169,15,262,161,2375,2016,2015-16,Stephen Curry
17063,458,Russell Westbrook,PG,28,OKC,81,81,2802,824,1941,...,864,840,132,31,438,190,2558,2017,2016-17,Russell Westbrook
17332,194,James Harden,SG,28,HOU,72,72,2551,651,1449,...,389,630,126,50,315,169,2191,2018,2017-18,James Harden
17783,18,Giannis Antetokounmpo,PF,24,MIL,72,72,2358,721,1247,...,898,424,92,110,268,232,1994,2019,2018-19,Giannis Antetokounmpo
18484,13,Giannis Antetokounmpo,PF,25,MIL,63,63,1917,685,1238,...,856,354,61,66,230,195,1857,2020,2019-20,Giannis Antetokounmpo

## Convert to .csv

In [67]:
df.to_csv('../data/all_Seasons_MVP.csv',index=False)