In [1]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

In [2]:
url = 'https://www.basketball-reference.com/leagues/NBA_{}_totals.html'

#Method to extract the information of players per season
def scrape_season_stats(base_url, year_start, year_end):
    years = range(year_start,year_end+1,1)

    df_season = pd.DataFrame()

    for year in years:
        print(f'Extracting data from the {year} season')
        request_url = base_url.format(year)
        req = requests.get(request_url)
        soup = BeautifulSoup(req.content, 'html.parser')
        table = soup.find('table', {'id':'totals_stats'})
        df = pd.read_html(str(table))[0]
        df['Year'] = year
        df['Season'] = f'{year-1}-{str(year)[2:]}'
        df_season = df_season.append(df)
    return df_season

In [3]:
#Using theMethod to extract the information of players per season
df_season = scrape_season_stats(url, 1985, 2020)

Extracting data from the 1985 season
Extracting data from the 1986 season
Extracting data from the 1987 season
Extracting data from the 1988 season
Extracting data from the 1989 season
Extracting data from the 1990 season
Extracting data from the 1991 season
Extracting data from the 1992 season
Extracting data from the 1993 season
Extracting data from the 1994 season
Extracting data from the 1995 season
Extracting data from the 1996 season
Extracting data from the 1997 season
Extracting data from the 1998 season
Extracting data from the 1999 season
Extracting data from the 2000 season
Extracting data from the 2001 season
Extracting data from the 2002 season
Extracting data from the 2003 season
Extracting data from the 2004 season
Extracting data from the 2005 season
Extracting data from the 2006 season
Extracting data from the 2007 season
Extracting data from the 2008 season
Extracting data from the 2009 season
Extracting data from the 2010 season
Extracting data from the 2011 season
Extracting data from the 2012 season
Extracting data from the 2013 season
Extracting data from the 2014 season
Extracting data from the 2015 season
Extracting data from the 2016 season
Extracting data from the 2017 season
Extracting data from the 2018 season
Extracting data from the 2019 season
Extracting data from the 2020 season

In [4]:
#Cleaning from the data extracted in the method to use them
df_season_clean = df_season[~(df_season['Rk'] == 'Rk')]
df_season_clean

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Year,Season
0,1,Kareem Abdul-Jabbar*,C,37,LAL,79,79,2630,723,1207,...,460,622,249,63,162,197,238,1735,1985,1984-85
1,2,Alvan Adams,PF,30,PHO,82,69,2136,476,915,...,347,500,308,115,48,197,254,1202,1985,1984-85
2,3,Mark Aguirre,SF,25,DAL,80,79,2699,794,1569,...,289,477,249,60,24,253,250,2055,1985,1984-85
3,4,Danny Ainge,SG,25,BOS,75,73,2564,419,792,...,192,268,399,122,6,149,228,971,1985,1984-85
4,5,Chuck Aleksinas,C,25,GSW,74,4,1114,161,337,...,183,270,36,15,15,72,171,377,1985,1984-85
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
672,525,Trae Young,PG,21,ATL,60,60,2120,546,1249,...,223,255,560,65,8,289,104,1778,2020,2019-20
673,526,Cody Zeller,C,27,CHO,58,39,1341,251,479,...,251,411,88,40,25,75,140,642,2020,2019-20
674,527,Tyler Zeller,C,30,SAS,2,0,4,1,4,...,1,4,0,0,0,0,0,2,2020,2019-20
675,528,Ante Žižić,C,23,CLE,22,0,221,41,72,...,48,66,6,7,5,10,27,96,2020,2019-20
676,529,Ivica Zubac,C,22,LAC,72,70,1326,236,385,...,346,543,82,16,66,61,168,596,2020,2019-20

In [5]:
#Writing CSV of season stats
df_season_clean.to_csv('season_stats.csv')

In [6]:
#Extract the information of all Seasons
request_url = 'https://www.basketball-reference.com/leagues/'
req = requests.get(request_url)
soup = BeautifulSoup(req.content, 'html.parser')
table = soup.find('table', {'id':'stats'})
df_total = pd.read_html(str(table))[0]

In [7]:
df_total

   Unnamed: 0_level_0 Unnamed: 1_level_0     Unnamed: 2_level_0  \
               Season                 Lg               Champion
0             2019-20                NBA     Los Angeles Lakers
1             2018-19                NBA        Toronto Raptors
2             2017-18                NBA  Golden State Warriors
3             2016-17                NBA  Golden State Warriors
4             2015-16                NBA    Cleveland Cavaliers
..                ...                ...                    ...
78            1950-51                NBA       Rochester Royals
79            1949-50                NBA     Minneapolis Lakers
80            1948-49                BAA     Minneapolis Lakers
81            1947-48                BAA      Baltimore Bullets
82            1946-47                BAA  Philadelphia Warriors

       Award Winners                          Top Performers  \
                 MVP Rookie of the Year               Points
0   G. Antetokounmpo          J. Morant     J. Harden (2335)
1   G. Antetokounmpo          L. Dončić     J. Harden (2818)
2          J. Harden         B. Simmons      L. James (2251)
3       R. Westbrook         M. Brogdon  R. Westbrook (2558)
4           S. Curry           K. Towns     J. Harden (2376)
..               ...                ...                  ...
78               NaN          P. Arizin      G. Mikan (1932)
79               NaN           A. Groza      G. Mikan (1865)
80               NaN         H. Shannon      G. Mikan (1698)
81               NaN         P. Hoffman  M. Zaslofsky (1007)
82               NaN                NaN      J. Fulks (1389)


              Rebounds             Assists         Win Shares
0      R. Gobert (916)      L. James (684)   J. Harden (13.1)
1   A. Drummond (1232)  R. Westbrook (784)   J. Harden (15.2)
2   A. Drummond (1247)  R. Westbrook (820)   J. Harden (15.4)
3   A. Drummond (1115)     J. Harden (907)   J. Harden (15.0)
4   A. Drummond (1198)      R. Rondo (839)    S. Curry (17.9)
..                 ...                 ...                ...
78   D. Schayes (1080)    A. Phillip (414)    G. Mikan (23.4)
79                 NaN    D. McGuire (386)    G. Mikan (21.1)
80                 NaN     B. Davies (321)    G. Mikan (20.9)
81                 NaN    H. Dallmar (120)  B. Feerick (10.5)
82                 NaN  E. Calverley (202)  B. Feerick (18.6)

[83 rows x 9 columns]